defmodule Polyphony.Authoring.QuickBuildTest do
  @moduledoc """
  Quick Build scaffolds a whole campaign from seeds: a world bible, one character per
  seed line (grounded in the world, cross-linked), and a premise — all persisted to the
  author's library. Driven by the offline Mock so generation is deterministic.
  """
  use ExUnit.Case, async: false

  alias Polyphony.{Library, Owner, Repo}
  alias Polyphony.Authoring.{CharacterSheet, QuickBuild, WorldBible}
  alias Polyphony.Authoring.CharacterSheet.Boundary

  setup do
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(Repo)
    previous = Application.get_env(:polyphony, :llm)
    Application.put_env(:polyphony, :llm, provider: Polyphony.LLM.Mock)
    on_exit(fn -> Application.put_env(:polyphony, :llm, previous) end)
    %{owner: Owner.user("quick-build-#{System.unique_integer([:positive])}")}
  end

  test "builds a world, a cast, cross-links relationships, and a premise", %{owner: owner} do
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a rain-drowned harbor city",
        character_seeds: ["a disgraced harbor-master", "the collector who bought her past"],
        provider: Polyphony.LLM.Mock
      )

    # A world bible, persisted and returned.
    assert %WorldBible{} = wb = Library.payload(result.bible)
    assert wb.name not in [nil, ""]
    assert Library.get(result.bible.id).kind == "world_bible"

    # One :full character per seed line, linked to the world.
    assert length(result.characters) == 2

    for entry <- result.characters do
      sheet = Library.payload(entry)
      assert %CharacterSheet{status: :full} = sheet
      assert sheet.world_bible_id == result.bible.id
      assert sheet.premise not in [nil, ""]
      # Boundaries are generated too (same as the editor's "Generate all fields"), and
      # every generated one is a conditional slow-burn with a real condition.
      assert sheet.boundaries != []

      assert Enum.all?(
               sheet.boundaries,
               &match?(%Boundary{stance: :conditional, condition: c} when c not in [nil, ""], &1)
             )
    end

    # Cross-linked: each character regards the other, by stable id AND with a role
    # (a non-empty descriptor) — not a bare, role-less link.
    [a, b] = result.characters
    sheet_a = Library.payload(a)
    assert [rel] = sheet_a.relationships
    assert rel.target_id == b.id
    assert rel.descriptor not in [nil, ""]

    # A premise came back.
    assert is_binary(result.premise) and result.premise != ""
  end

  test "every character gets what's true about them, and their pronouns", %{owner: owner} do
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a rain-drowned harbor city",
        character_seeds: ["a disgraced harbor-master"],
        provider: Polyphony.LLM.Mock
      )

    [sheet] = Enum.map(result.characters, &Library.payload/1)

    # Both were generated by `Autofill` all along and dropped on the floor in the
    # mapping, so a quick-built character arrived with no facts at all and left the
    # model inferring pronouns from a name every time it wrote them.
    assert sheet.facts != []
    assert Enum.all?(sheet.facts, &(String.trim(&1.statement) != ""))
    assert sheet.pronouns not in [nil, ""]

    # Public, every one. Concealment is an authoring decision, and a build that guessed
    # would be deciding what a character may know on the author's behalf.
    assert Enum.all?(sheet.facts, &(&1.concealed == false))
  end

  test "the world and every character get a cover", %{owner: owner} do
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a rain-drowned harbor city",
        character_seeds: ["a disgraced harbor-master", "the collector"],
        provider: Polyphony.LLM.Mock
      )

    # The only part a stranger reads before taking either — and the returned entries
    # carry it, not just the rows, since the LiveView attaches what it is handed.
    assert Library.payload(result.bible).cover not in [nil, ""]
    assert Library.payload(Library.get(result.bible.id)).cover not in [nil, ""]

    for entry <- result.characters do
      assert Library.payload(entry).cover not in [nil, ""]
      assert Library.payload(Library.get(entry.id)).cover not in [nil, ""]
    end
  end

  test "the whole cast lands in the owner's library", %{owner: owner} do
    before = Enum.count(Library.list_for_owner(owner))

    {:ok, _result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "neon arcology",
        character_seeds: ["a courier", "a fixer", "a ghost"],
        provider: Polyphony.LLM.Mock
      )

    entries = Library.list_for_owner(owner)
    # 1 world + 3 characters added.
    assert Enum.count(entries) == before + 4
    assert Enum.count(entries, &(&1.kind == "character")) == 3
    assert Enum.count(entries, &(&1.kind == "world_bible")) == 1
  end

  test "with off-screen suggestions on, each character stubs extra people", %{owner: owner} do
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a rain-drowned harbor city",
        character_seeds: ["a disgraced harbor-master", "the collector who bought her past"],
        suggest_offscreen: true,
        provider: Polyphony.LLM.Mock
      )

    chars = Enum.filter(Library.list_for_owner(owner), &(&1.kind == "character"))
    stubs = Enum.filter(chars, &match?(%CharacterSheet{status: :stub}, Library.payload(&1)))

    # The two main cast plus stubbed off-screen people.
    assert length(chars) > 2
    assert stubs != []

    # Stubs are still off the campaign roster — only the main cast is returned.
    assert length(result.characters) == 2

    # Each stub is pending, linked to the world, and its inbound relationships all point
    # back at the main cast that introduced it.
    main_ids = Enum.map(result.characters, & &1.id)

    for stub <- stubs do
      sheet = Library.payload(stub)
      assert sheet.status == :stub
      assert sheet.world_bible_id == result.bible.id
      assert sheet.relationships != []
      assert Enum.all?(sheet.relationships, &(&1.target_id in main_ids))
    end

    # A main character links to at least one off-screen stub (target_id set to a stub).
    stub_ids = MapSet.new(stubs, & &1.id)
    main = Library.payload(hd(result.characters))
    assert Enum.any?(main.relationships, &(&1.target_id in stub_ids))
  end

  defmodule SharedPersonProvider do
    @moduledoc "Mock, but every relationship suggestion names the SAME off-screen person."
    @behaviour Polyphony.LLM.Provider

    @impl true
    def complete(messages, opts) do
      if Keyword.get(opts, :response) == :relationships do
        {:ok, Jason.encode!([%{"target" => "Marek the Landlord", "descriptor" => "landlord"}])}
      else
        Polyphony.LLM.Mock.complete(messages, opts)
      end
    end
  end

  test "an off-screen person named by two characters collapses into one shared stub",
       %{owner: owner} do
    # Both characters name the same off-screen person; the shared stub registry must
    # collapse them into one stub that links back to both (not two duplicate Mareks).
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a walled city",
        character_seeds: ["a merchant", "a guard"],
        suggest_offscreen: true,
        provider: SharedPersonProvider
      )

    chars = Enum.filter(Library.list_for_owner(owner), &(&1.kind == "character"))
    stubs = Enum.filter(chars, &match?(%CharacterSheet{status: :stub}, Library.payload(&1)))
    main_ids = Enum.sort(Enum.map(result.characters, & &1.id))

    # Exactly one stub — the landlord, reused, not re-created per character.
    assert [stub] = stubs
    assert String.downcase(Library.payload(stub).name) == "marek the landlord"

    # It links back to BOTH main characters.
    ids = Library.payload(stub).relationships |> Enum.map(& &1.target_id) |> Enum.sort()
    assert ids == main_ids
  end

  defmodule SpyProvider do
    @moduledoc "Mock, but echoes each character-generation prompt to the test process."
    @behaviour Polyphony.LLM.Provider

    @impl true
    def complete(messages, opts) do
      if Keyword.get(opts, :response) == :autofill do
        pid = Application.get_env(:polyphony, :spy_pid)
        if pid, do: send(pid, {:autofill, Enum.map_join(messages, " ", & &1.content)})
      end

      Polyphony.LLM.Mock.complete(messages, opts)
    end
  end

  test "a later character is generated with the earlier cast in context", %{owner: owner} do
    Application.put_env(:polyphony, :spy_pid, self())
    on_exit(fn -> Application.delete_env(:polyphony, :spy_pid) end)

    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a walled city",
        character_seeds: ["the first", "the second"],
        provider: SpyProvider
      )

    first_name = hd(result.characters) |> Library.payload() |> Map.get(:name)
    prompts = collect_autofill([])

    # The first character's generated name only appears in a prompt if a *later*
    # character was grounded in it — proving the cast accumulates as context.
    assert first_name not in [nil, ""]
    assert Enum.any?(prompts, &String.contains?(&1, first_name))
  end

  defp collect_autofill(acc) do
    receive do
      {:autofill, text} -> collect_autofill([text | acc])
    after
      0 -> acc
    end
  end

  test "off-screen suggestions are off by default (cast-only interlink)", %{owner: owner} do
    {:ok, _result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a quiet village",
        character_seeds: ["a baker", "a constable"],
        provider: Polyphony.LLM.Mock
      )

    chars = Enum.filter(Library.list_for_owner(owner), &(&1.kind == "character"))
    # Exactly the two main cast — no stubs.
    assert length(chars) == 2
    assert Enum.all?(chars, &match?(%CharacterSheet{status: :full}, Library.payload(&1)))
  end

  defmodule OneBadProvider do
    @moduledoc """
    Mock, except an autofill brief containing BOOMCHAR generates blank (no usable fields)
    and one containing BOOMFAIL errors outright — for exercising partial/total failure.
    """
    @behaviour Polyphony.LLM.Provider

    @impl true
    def complete(messages, opts) do
      # Only the character's OWN seed counts — not another character named in the
      # ensemble-context roster (which is appended after "Ensemble context").
      primary =
        messages |> Enum.map_join(" ", & &1.content) |> String.split("Ensemble context") |> hd()

      cond do
        Keyword.get(opts, :response) == :autofill and String.contains?(primary, "BOOMFAIL") ->
          {:error, :boom}

        Keyword.get(opts, :response) == :autofill and String.contains?(primary, "BOOMCHAR") ->
          {:ok, "{}"}

        true ->
          Polyphony.LLM.Mock.complete(messages, opts)
      end
    end
  end

  test "a single character failure keeps the world, the rest of the cast, and the premise",
       %{owner: owner} do
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a harbor city",
        character_seeds: ["a good sailor", "BOOMCHAR the doomed"],
        provider: OneBadProvider
      )

    # The world, the one good character, and the premise survive.
    assert %WorldBible{} = Library.payload(result.bible)
    assert length(result.characters) == 1
    assert result.premise != ""

    # The failed seed is reported, not silently dropped.
    assert [{"BOOMCHAR the doomed", :blank_generation}] = result.failed
  end

  test "even if every character fails, the world still builds and is returned",
       %{owner: owner} do
    # The world is the only hard requirement — a fully-failed cast must not discard it,
    # or the campaign loses its association to the world that did generate.
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a harbor city",
        character_seeds: ["BOOMCHAR one", "BOOMCHAR two"],
        provider: OneBadProvider
      )

    assert %WorldBible{} = Library.payload(result.bible)
    assert result.characters == []
    assert length(result.failed) == 2
  end

  test "a failed world is the one thing that aborts the build", %{owner: owner} do
    assert {:error, {:world_failed, _}} =
             QuickBuild.build(
               owner: owner,
               world_seed: "BOOMFAIL a doomed world",
               character_seeds: ["a sailor"],
               provider: OneBadProvider
             )
  end

  test "reports progress through each phase", %{owner: owner} do
    me = self()

    {:ok, _result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a harbor city",
        character_seeds: ["a sailor", "a fixer"],
        provider: Polyphony.LLM.Mock,
        progress: fn step -> send(me, {:progress, step}) end
      )

    steps = collect_progress([])

    # world + 2 characters + linking + premise + covers = 6, and the bar reaches full.
    assert Enum.all?(steps, &(&1.total == 6))
    assert List.last(steps).done == 6
    assert Enum.map(steps, & &1.done) == Enum.sort(Enum.map(steps, & &1.done))

    labels = Enum.map(steps, & &1.label)
    assert "Dreaming up the world" in labels
    assert "Writing character 1 of 2" in labels
    assert "Framing the premise" in labels
    assert "Writing the covers" in labels
  end

  defp collect_progress(acc) do
    receive do
      {:progress, step} -> collect_progress([step | acc])
    after
      0 -> Enum.reverse(acc)
    end
  end

  test "a blank seed still generates a character (one per row)", %{owner: owner} do
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a harbor city",
        # Three rows, one of them blank — all three become characters.
        character_seeds: ["a sailor", "", "a fixer"],
        provider: Polyphony.LLM.Mock
      )

    assert length(result.characters) == 3

    for entry <- result.characters do
      sheet = Library.payload(entry)
      assert %CharacterSheet{status: :full} = sheet
      assert sheet.name not in [nil, ""]
    end
  end

  test "a blank character list still builds a world and premise", %{owner: owner} do
    {:ok, result} =
      QuickBuild.build(
        owner: owner,
        world_seed: "a quiet village",
        character_seeds: [],
        provider: Polyphony.LLM.Mock
      )

    assert result.characters == []
    assert %WorldBible{} = Library.payload(result.bible)
    assert result.premise != ""
  end
end
