defmodule Polyphony.Characters do
  @moduledoc """
  Characters as library entries: listing them, and moving them between **cast
  tiers** (`backend-backlog.md` §2.5).

  Sits beside `Polyphony.Groups` and for the same reason — the storage, ownership,
  archiving and versioning are `Polyphony.Library`'s job, and what lives here is
  only the part that is specific to characters.

  ## Why a tier is not a status

  `CharacterSheet.status` (`:stub | :proposed | :full`) says whether the sheet is
  *written*. It stopped being able to say anything else the moment the design
  settled that **no character ever plays without a full sheet** — admitting a
  walk-on autogenerates one rather than admitting a stub, so if everyone who plays
  is `:full`, status no longer distinguishes the bellman from the lead.

  `tier` is the second axis: **context residency**. `:main` and `:recurring` stay
  resident; `:incidental` is loaded only for the scenes they appear in. That is
  what keeps an autogenerated cast from growing context without bound, and it is
  what the cast list sorts and groups by.

  ## Promotion and demotion are both real

  Deliberately symmetric. A walk-on who turns out to matter is promoted; a
  character who has served their purpose is **demoted rather than deleted**, because
  deletion would lose someone the transcript still refers to. `promote/2` and
  `demote/2` step one place along `CharacterSheet.tiers/0` and saturate at the ends,
  so the buttons are always safe to press.

  ## What isn't here yet

  Nothing *consumes* residency, because there is nothing to consume it from: the
  Director's roster is a scene's own cast (`Context.Rebuild.roster/1`), not a
  campaign-wide one, so no read currently has to choose who stays in the room when
  they aren't in the room. That choice arrives with autogeneration-on-admit — the
  rest of §2.5 — and `resident?/1` is the predicate it will ask.
  """

  alias Polyphony.Authoring.CharacterSheet
  alias Polyphony.Library

  @kind "character"

  @doc "The kind under which characters are stored in the library."
  @spec kind() :: String.t()
  def kind, do: @kind

  @doc "Every character owned by `owner`, newest last."
  @spec list(term(), keyword()) :: [map()]
  def list(owner, opts \\ []) do
    owner
    |> Library.list_for_owner(opts)
    |> Enum.filter(&(&1.kind == @kind))
  end

  @doc "The sheet behind a library entry id, or nil if it isn't a character."
  @spec get(term(), keyword()) :: CharacterSheet.t() | nil
  def get(id, opts \\ []) do
    with entry when not is_nil(entry) <- Library.get(id, opts),
         %CharacterSheet{} = sheet <- Library.payload(entry) do
      sheet
    else
      _ -> nil
    end
  end

  @doc """
  Move a character to `tier` outright. An unknown tier is rejected rather than
  silently stored — a bad tier would quietly change who stays in context.
  """
  @spec set_tier(term(), CharacterSheet.tier(), keyword()) :: {:ok, map()} | {:error, term()}
  def set_tier(id, tier, opts \\ []) do
    if tier in CharacterSheet.tiers() do
      update(id, opts, &%CharacterSheet{&1 | tier: tier})
    else
      {:error, {:unknown_tier, tier}}
    end
  end

  @doc "Move a character one tier up (`:incidental → :recurring → :main`); a no-op at the top."
  @spec promote(term(), keyword()) :: {:ok, map()} | {:error, term()}
  def promote(id, opts \\ []), do: step(id, -1, opts)

  @doc "Move a character one tier down (`:main → :recurring → :incidental`); a no-op at the bottom."
  @spec demote(term(), keyword()) :: {:ok, map()} | {:error, term()}
  def demote(id, opts \\ []), do: step(id, +1, opts)

  @doc """
  Group library entries into the cast list's sections — `[{tier, label, entries}]`
  in `CharacterSheet.tiers/0` order, with empty sections dropped.

  Entry order within a section is preserved, so whatever the caller sorted by
  survives the grouping. A payload that isn't a character sheet, or one with an
  unrecognised tier, lands in `:main` — the same fail-toward-visible default the
  struct itself has.
  """
  @spec by_tier([map()]) :: [{CharacterSheet.tier(), String.t(), [map()]}]
  def by_tier(entries) do
    grouped = Enum.group_by(entries, &tier_of/1)

    for tier <- CharacterSheet.tiers(),
        members = Map.get(grouped, tier, []),
        members != [],
        do: {tier, CharacterSheet.tier_label(tier), members}
  end

  @doc "The entries that stay in context between scenes (`:main` + `:recurring`)."
  @spec resident([map()]) :: [map()]
  def resident(entries), do: Enum.filter(entries, &CharacterSheet.resident?(tier_of(&1)))

  @doc "The tier of a library entry, defaulting to `:main` for anything unreadable."
  @spec tier_of(map()) :: CharacterSheet.tier()
  def tier_of(entry) do
    case Library.payload(entry) do
      %CharacterSheet{tier: tier} when tier in [:main, :recurring, :incidental] -> tier
      _ -> :main
    end
  end

  defp step(id, delta, opts) do
    case get(id, opts) do
      %CharacterSheet{} = sheet ->
        tiers = CharacterSheet.tiers()
        at = Enum.find_index(tiers, &(&1 == sheet.tier)) || 0
        next = Enum.at(tiers, min(max(at + delta, 0), length(tiers) - 1))
        Library.update_payload(id, %CharacterSheet{sheet | tier: next}, opts)

      _ ->
        {:error, :not_found}
    end
  end

  defp update(id, opts, fun) do
    case get(id, opts) do
      %CharacterSheet{} = sheet -> Library.update_payload(id, fun.(sheet), opts)
      _ -> {:error, :not_found}
    end
  end
end
